Class {
	#name : #APMaTest6,
	#superclass : #APartWithForm,
	#category : #'Apart-Magritte'
}

{ #category : #accessing }
APMaTest6 >> defineAspects [

	<generated>
	^ partInterface description createAllAspectsNamed: #(  )
]

{ #category : #accessing }
APMaTest6 >> initializeDefaultValues [

	<generated>
	
]

{ #category : #accessing }
APMaTest6 >> initializeValues [

	<generated>
	self initializeDefaultValues
]
